/**
 * frontend/src/lib/medicalLexicon.ts
 * In-memory Clinical Medical Lexicon, RxNorm Medications, Clinical Dosages & Latin Sig Codes.
 * Provides sub-millisecond prefix, substring, and length-adaptive Damerau-Levenshtein fuzzy matching.
 */

export type MedicalCategory =
  | 'medication'
  | 'dosage'
  | 'sig_frequency'
  | 'sig_route'
  | 'sig_timing'
  | 'dosage_form'
  | 'instruction';

export interface MedicalLexiconEntry {
  term: string;
  category: MedicalCategory;
  normalized: string;
  frequencyScore: number; // 0.0 to 100.0
  description: string;
  brandNames?: string[];
  standardStrengths?: string[];
  therapeuticClass?: string;
  isLasa?: boolean;
  lasaConfusionWith?: string;
  lasaWarning?: string;
}

export interface AutocompleteSuggestion {
  entry: MedicalLexiconEntry;
  matchType: 'exact' | 'prefix' | 'substring' | 'fuzzy';
  score: number;
  highlightIndices: [number, number]; // [start, end]
}

// Alias for AutocompleteSuggestion
export type LexiconMatch = AutocompleteSuggestion;

export interface LexiconSearchOptions {
  query: string;
  categoryFilter?: MedicalCategory | MedicalCategory[];
  maxResults?: number;
  contextPreviousWord?: string;
  enableFuzzy?: boolean;
}

// 1. Top RxNorm Generic & Brand Medications (150+ items)
const RXNORM_MEDICATIONS: MedicalLexiconEntry[] = [
  {
    term: 'Amoxicillin',
    category: 'medication',
    normalized: 'amoxicillin',
    frequencyScore: 99,
    description: 'Aminopenicillin antibiotic for respiratory & otitis media bacterial infections',
    brandNames: ['Amoxil', 'Moxatag', 'Trimox'],
    standardStrengths: ['250mg', '500mg', '875mg', '125mg/5mL', '250mg/5mL'],
    therapeuticClass: 'Antibiotics',
    isLasa: true,
    lasaConfusionWith: 'Ampicillin',
    lasaWarning: 'Do not confuse with Ampicillin (oral vs IV distinction).',
  },
  {
    term: 'Ampicillin',
    category: 'medication',
    normalized: 'ampicillin',
    frequencyScore: 75,
    description: 'Aminopenicillin antibiotic primarily for IV enterococcal & listeria coverage',
    brandNames: ['Principen', 'Omnipen'],
    standardStrengths: ['250mg', '500mg', '1g', '2g'],
    therapeuticClass: 'Antibiotics',
    isLasa: true,
    lasaConfusionWith: 'Amoxicillin',
    lasaWarning: 'Do not confuse with Amoxicillin.',
  },
  {
    term: 'Lisinopril',
    category: 'medication',
    normalized: 'lisinopril',
    frequencyScore: 99,
    description: 'ACE inhibitor for hypertension & heart failure',
    brandNames: ['Zestril', 'Prinivil', 'Qbrelis'],
    standardStrengths: ['2.5mg', '5mg', '10mg', '20mg', '40mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Metformin',
    category: 'medication',
    normalized: 'metformin',
    frequencyScore: 98,
    description: 'Biguanide antidiabetic for type 2 diabetes mellitus',
    brandNames: ['Glucophage', 'Fortamet', 'Glumetza', 'Riomet'],
    standardStrengths: ['500mg', '850mg', '1000mg', '500mg ER', '750mg ER'],
    therapeuticClass: 'Endocrine & Diabetes',
    isLasa: true,
    lasaConfusionWith: 'Metronidazole',
    lasaWarning: 'Do not confuse with Metronidazole (antibacterial/antiprotozoal).',
  },
  {
    term: 'Metronidazole',
    category: 'medication',
    normalized: 'metronidazole',
    frequencyScore: 86,
    description: 'Nitroimidazole antimicrobial for anaerobic & protozoal infections',
    brandNames: ['Flagyl'],
    standardStrengths: ['250mg', '500mg'],
    therapeuticClass: 'Antibiotics',
    isLasa: true,
    lasaConfusionWith: 'Metformin',
    lasaWarning: 'Do not confuse with Metformin.',
  },
  {
    term: 'Atorvastatin',
    category: 'medication',
    normalized: 'atorvastatin',
    frequencyScore: 99,
    description: 'HMG-CoA reductase inhibitor (Statin) for hypercholesterolemia & ASCVD',
    brandNames: ['Lipitor'],
    standardStrengths: ['10mg', '20mg', '40mg', '80mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Levothyroxine',
    category: 'medication',
    normalized: 'levothyroxine',
    frequencyScore: 98,
    description: 'Synthetic T4 thyroid hormone for hypothyroidism',
    brandNames: ['Synthroid', 'Levoxyl', 'Tirosint', 'Unithroid'],
    standardStrengths: ['25mcg', '50mcg', '75mcg', '88mcg', '100mcg', '112mcg', '125mcg', '150mcg', '175mcg', '200mcg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Omeprazole',
    category: 'medication',
    normalized: 'omeprazole',
    frequencyScore: 97,
    description: 'Proton Pump Inhibitor (PPI) for GERD & peptic ulcer disease',
    brandNames: ['Prilosec', 'Zegerid'],
    standardStrengths: ['10mg', '20mg', '40mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Amlodipine',
    category: 'medication',
    normalized: 'amlodipine',
    frequencyScore: 98,
    description: 'Dihydropyridine calcium channel blocker for hypertension & chronic stable angina',
    brandNames: ['Norvasc', 'Katerzia'],
    standardStrengths: ['2.5mg', '5mg', '10mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Losartan',
    category: 'medication',
    normalized: 'losartan',
    frequencyScore: 96,
    description: 'Angiotensin II receptor blocker (ARB) for hypertension & nephropathy',
    brandNames: ['Cozaar'],
    standardStrengths: ['25mg', '50mg', '100mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Gabapentin',
    category: 'medication',
    normalized: 'gabapentin',
    frequencyScore: 95,
    description: 'GABA analog for postherpetic neuralgia & partial seizures',
    brandNames: ['Neurontin', 'Gralise', 'Horizant'],
    standardStrengths: ['100mg', '300mg', '400mg', '600mg', '800mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Hydrochlorothiazide',
    category: 'medication',
    normalized: 'hydrochlorothiazide',
    frequencyScore: 96,
    description: 'Thiazide diuretic for hypertension & peripheral edema',
    brandNames: ['Microzide'],
    standardStrengths: ['12.5mg', '25mg', '50mg'],
    therapeuticClass: 'Cardiovascular',
    isLasa: true,
    lasaConfusionWith: 'Hydralazine',
    lasaWarning: 'Do not confuse with Hydralazine (vasodilator) or Hydroxyzine.',
  },
  {
    term: 'Hydralazine',
    category: 'medication',
    normalized: 'hydralazine',
    frequencyScore: 82,
    description: 'Direct-acting arterial vasodilator for severe hypertension & heart failure',
    brandNames: ['Apresoline'],
    standardStrengths: ['10mg', '25mg', '50mg', '100mg'],
    therapeuticClass: 'Cardiovascular',
    isLasa: true,
    lasaConfusionWith: 'Hydrochlorothiazide',
    lasaWarning: 'Do not confuse with Hydrochlorothiazide or Hydroxyzine.',
  },
  {
    term: 'Hydroxyzine',
    category: 'medication',
    normalized: 'hydroxyzine',
    frequencyScore: 84,
    description: 'First-generation antihistamine with anxiolytic and sedative properties',
    brandNames: ['Atarax', 'Vistaril'],
    standardStrengths: ['10mg', '25mg', '50mg', '100mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Hydralazine',
    lasaWarning: 'Do not confuse with Hydralazine.',
  },
  {
    term: 'Sertraline',
    category: 'medication',
    normalized: 'sertraline',
    frequencyScore: 95,
    description: 'SSRI antidepressant for MDD, OCD, panic disorder & PTSD',
    brandNames: ['Zoloft'],
    standardStrengths: ['25mg', '50mg', '100mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Simvastatin',
    category: 'medication',
    normalized: 'simvastatin',
    frequencyScore: 93,
    description: 'HMG-CoA reductase inhibitor for dyslipidemia',
    brandNames: ['Zocor'],
    standardStrengths: ['10mg', '20mg', '40mg', '80mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Montelukast',
    category: 'medication',
    normalized: 'montelukast',
    frequencyScore: 94,
    description: 'Leukotriene receptor antagonist for asthma maintenance & allergic rhinitis',
    brandNames: ['Singulair'],
    standardStrengths: ['4mg', '5mg', '10mg'],
    therapeuticClass: 'Respiratory',
  },
  {
    term: 'Escitalopram',
    category: 'medication',
    normalized: 'escitalopram',
    frequencyScore: 94,
    description: 'SSRI antidepressant for generalized anxiety disorder & MDD',
    brandNames: ['Lexapro'],
    standardStrengths: ['5mg', '10mg', '20mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Prednisone',
    category: 'medication',
    normalized: 'prednisone',
    frequencyScore: 94,
    description: 'Glucocorticoid corticosteroid for acute inflammation & immunosuppression',
    brandNames: ['Deltasone', 'Rayos'],
    standardStrengths: ['1mg', '2.5mg', '5mg', '10mg', '20mg', '50mg'],
    therapeuticClass: 'Endocrine & Diabetes',
    isLasa: true,
    lasaConfusionWith: 'Prednisolone',
    lasaWarning: 'Do not confuse with Prednisolone (pediatric liquid / liver failure preference).',
  },
  {
    term: 'Prednisolone',
    category: 'medication',
    normalized: 'prednisolone',
    frequencyScore: 80,
    description: 'Active corticosteroid metabolite for pediatric and hepatic inflammation',
    brandNames: ['Orapred', 'Prelone', 'Pediapred'],
    standardStrengths: ['5mg', '15mg', '25mg', '15mg/5mL'],
    therapeuticClass: 'Endocrine & Diabetes',
    isLasa: true,
    lasaConfusionWith: 'Prednisone',
    lasaWarning: 'Do not confuse with Prednisone.',
  },
  {
    term: 'Ibuprofen',
    category: 'medication',
    normalized: 'ibuprofen',
    frequencyScore: 97,
    description: 'NSAID analgesic, anti-inflammatory & antipyretic',
    brandNames: ['Advil', 'Motrin', 'Caldolor'],
    standardStrengths: ['200mg', '400mg', '600mg', '800mg', '100mg/5mL'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Acetaminophen',
    category: 'medication',
    normalized: 'acetaminophen',
    frequencyScore: 99,
    description: 'Non-opioid analgesic and antipyretic (APAP / Paracetamol)',
    brandNames: ['Tylenol', 'Ofirmev', 'Mapap'],
    standardStrengths: ['325mg', '500mg', '650mg', '160mg/5mL'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Ciprofloxacin',
    category: 'medication',
    normalized: 'ciprofloxacin',
    frequencyScore: 89,
    description: 'Fluoroquinolone antibiotic for complicated UTI, prostatitis & gastroenteritis',
    brandNames: ['Cipro', 'Cipro XR'],
    standardStrengths: ['250mg', '500mg', '750mg'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Azithromycin',
    category: 'medication',
    normalized: 'azithromycin',
    frequencyScore: 93,
    description: 'Macrolide antibiotic for CAP, sinusitis & skin infections (Z-Pak)',
    brandNames: ['Zithromax', 'Z-Pak', 'Zmax'],
    standardStrengths: ['250mg', '500mg', '600mg', '100mg/5mL', '200mg/5mL'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Cephalexin',
    category: 'medication',
    normalized: 'cephalexin',
    frequencyScore: 91,
    description: 'First-generation cephalosporin for cellulitis, osteomyelitis & strep',
    brandNames: ['Keflex'],
    standardStrengths: ['250mg', '500mg', '750mg', '125mg/5mL', '250mg/5mL'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Doxycycline',
    category: 'medication',
    normalized: 'doxycycline',
    frequencyScore: 90,
    description: 'Tetracycline antibiotic for Lyme disease, acne & atypical pneumonia',
    brandNames: ['Vibramycin', 'Doryx', 'Monodox', 'Oracea'],
    standardStrengths: ['50mg', '100mg', '150mg'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Furosemide',
    category: 'medication',
    normalized: 'furosemide',
    frequencyScore: 94,
    description: 'Loop diuretic for acute pulmonary edema & CHF fluid overload',
    brandNames: ['Lasix'],
    standardStrengths: ['20mg', '40mg', '80mg', '10mg/mL'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Pantoprazole',
    category: 'medication',
    normalized: 'pantoprazole',
    frequencyScore: 93,
    description: 'Proton pump inhibitor for GERD, erosive esophagitis & Zollinger-Ellison',
    brandNames: ['Protonix'],
    standardStrengths: ['20mg', '40mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Tramadol',
    category: 'medication',
    normalized: 'tramadol',
    frequencyScore: 89,
    description: 'Centrally-acting mu-opioid receptor agonist and SNRI for moderate pain',
    brandNames: ['Ultram', 'ConZip', 'Qdolo'],
    standardStrengths: ['50mg', '100mg', '200mg', '300mg'],
    therapeuticClass: 'Analgesics & Opioids',
    isLasa: true,
    lasaConfusionWith: 'Trazodone',
    lasaWarning: 'Do not confuse with Trazodone (antidepressant/hypnotic).',
  },
  {
    term: 'Trazodone',
    category: 'medication',
    normalized: 'trazodone',
    frequencyScore: 90,
    description: 'Serotonin antagonist and reuptake inhibitor (SARI) for insomnia & depression',
    brandNames: ['Desyrel', 'Oleptro'],
    standardStrengths: ['50mg', '100mg', '150mg', '300mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Tramadol',
    lasaWarning: 'Do not confuse with Tramadol (opioid analgesic).',
  },
  {
    term: 'Albuterol',
    category: 'medication',
    normalized: 'albuterol',
    frequencyScore: 96,
    description: 'Short-acting beta-2 adrenergic agonist (SABA) for acute bronchospasm',
    brandNames: ['ProAir', 'Ventolin', 'Proventil', 'Accuneb'],
    standardStrengths: ['90mcg/actuation', '0.083% (2.5mg/3mL)', '0.5% (2.5mg/0.5mL)'],
    therapeuticClass: 'Respiratory',
  },
  {
    term: 'Warfarin',
    category: 'medication',
    normalized: 'warfarin',
    frequencyScore: 87,
    description: 'Vitamin K epoxide reductase antagonist anticoagulant (monitor INR)',
    brandNames: ['Coumadin', 'Jantoven'],
    standardStrengths: ['1mg', '2mg', '2.5mg', '3mg', '4mg', '5mg', '6mg', '7.5mg', '10mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Clopidogrel',
    category: 'medication',
    normalized: 'clopidogrel',
    frequencyScore: 92,
    description: 'Thienopyridine P2Y12 platelet inhibitor for post-MI & stent thrombosis',
    brandNames: ['Plavix'],
    standardStrengths: ['75mg', '300mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Metoprolol Tartrate',
    category: 'medication',
    normalized: 'metoprololtartrate',
    frequencyScore: 94,
    description: 'Immediate-release cardioselective beta-blocker for post-MI & angina',
    brandNames: ['Lopressor'],
    standardStrengths: ['25mg', '50mg', '100mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Metoprolol Succinate',
    category: 'medication',
    normalized: 'metoprololsuccinate',
    frequencyScore: 96,
    description: 'Extended-release beta-1 blocker for heart failure & hypertension (daily dosing)',
    brandNames: ['Toprol XL'],
    standardStrengths: ['25mg', '50mg', '100mg', '200mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Fluticasone Propionate',
    category: 'medication',
    normalized: 'fluticasonepropionate',
    frequencyScore: 93,
    description: 'Inhaled / nasal synthetic corticosteroid for allergic rhinitis & asthma',
    brandNames: ['Flonase', 'Flovent'],
    standardStrengths: ['50mcg spray', '44mcg', '110mcg', '220mcg'],
    therapeuticClass: 'Respiratory',
  },
  {
    term: 'Duloxetine',
    category: 'medication',
    normalized: 'duloxetine',
    frequencyScore: 91,
    description: 'SNRI for MDD, diabetic peripheral neuropathy, fibromyalgia & chronic musculoskeletal pain',
    brandNames: ['Cymbalta', 'Drizalma'],
    standardStrengths: ['20mg', '30mg', '60mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Rosuvastatin',
    category: 'medication',
    normalized: 'rosuvastatin',
    frequencyScore: 95,
    description: 'High-intensity statin for severe hypercholesterolemia & secondary prevention',
    brandNames: ['Crestor', 'Ezallor'],
    standardStrengths: ['5mg', '10mg', '20mg', '40mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Hydrocodone / Acetaminophen',
    category: 'medication',
    normalized: 'hydrocodoneacetaminophen',
    frequencyScore: 92,
    description: 'Schedule II opioid analgesic combination for moderate to severe acute pain',
    brandNames: ['Norco', 'Vicodin', 'Lortab'],
    standardStrengths: ['5/325mg', '7.5/325mg', '10/325mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Oxycodone / Acetaminophen',
    category: 'medication',
    normalized: 'oxycodoneacetaminophen',
    frequencyScore: 90,
    description: 'Schedule II semi-synthetic opioid combo for acute post-surgical pain',
    brandNames: ['Percocet', 'Endocet', 'Roxicet'],
    standardStrengths: ['5/325mg', '7.5/325mg', '10/325mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Oxycodone',
    category: 'medication',
    normalized: 'oxycodone',
    frequencyScore: 88,
    description: 'Pure opioid agonist for severe chronic or cancer pain',
    brandNames: ['OxyContin', 'Roxicodone', 'Oxaydo'],
    standardStrengths: ['5mg', '10mg', '15mg', '20mg', '30mg', '40mg', '80mg'],
    therapeuticClass: 'Analgesics & Opioids',
    isLasa: true,
    lasaConfusionWith: 'Oxycontin',
    lasaWarning: 'Confirm immediate-release (Roxicodone) vs extended-release (OxyContin).',
  },
  {
    term: 'Morphine Sulfate',
    category: 'medication',
    normalized: 'morphinesulfate',
    frequencyScore: 86,
    description: 'Gold standard opioid analgesic for severe visceral and palliative pain',
    brandNames: ['MS Contin', 'Kadian', 'Roxanol'],
    standardStrengths: ['15mg', '30mg', '60mg', '100mg', '200mg', '20mg/mL'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Zolpidem',
    category: 'medication',
    normalized: 'zolpidem',
    frequencyScore: 88,
    description: 'Non-benzodiazepine GABA-A receptor agonist for short-term insomnia',
    brandNames: ['Ambien', 'Ambien CR', 'Intermezzo', 'Edluar'],
    standardStrengths: ['5mg', '10mg', '6.25mg CR', '12.5mg CR'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Clonazepam',
    category: 'medication',
    normalized: 'clonazepam',
    frequencyScore: 89,
    description: 'Long-acting benzodiazepine for panic disorder and Lennox-Gastaut seizure syndrome',
    brandNames: ['Klonopin'],
    standardStrengths: ['0.5mg', '1mg', '2mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Clonidine',
    lasaWarning: 'Do not confuse with Clonidine (antihypertensive alpha-2 agonist).',
  },
  {
    term: 'Clonidine',
    category: 'medication',
    normalized: 'clonidine',
    frequencyScore: 87,
    description: 'Centrally-acting alpha-2 adrenergic agonist for hypertension & ADHD',
    brandNames: ['Catapres', 'Catapres-TTS', 'Kapvay'],
    standardStrengths: ['0.1mg', '0.2mg', '0.3mg', '0.1mg/24hr patch'],
    therapeuticClass: 'Cardiovascular',
    isLasa: true,
    lasaConfusionWith: 'Clonazepam',
    lasaWarning: 'Do not confuse with Clonazepam (benzodiazepine).',
  },
  {
    term: 'Lorazepam',
    category: 'medication',
    normalized: 'lorazepam',
    frequencyScore: 90,
    description: 'Intermediate-acting benzodiazepine for acute agitation, anxiety & status epilepticus',
    brandNames: ['Ativan', 'Lorazepam Intensol'],
    standardStrengths: ['0.5mg', '1mg', '2mg', '2mg/mL'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Alprazolam',
    category: 'medication',
    normalized: 'alprazolam',
    frequencyScore: 91,
    description: 'Short-acting high-potency triazolobenzodiazepine for severe panic & GAD',
    brandNames: ['Xanax', 'Xanax XR', 'Niravam'],
    standardStrengths: ['0.25mg', '0.5mg', '1mg', '2mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Celecoxib',
    category: 'medication',
    normalized: 'celecoxib',
    frequencyScore: 87,
    description: 'Selective COX-2 inhibitor NSAID for osteoarthritis & rheumatoid arthritis',
    brandNames: ['Celebrex', 'Elyxyb'],
    standardStrengths: ['50mg', '100mg', '200mg', '400mg'],
    therapeuticClass: 'Analgesics & Opioids',
    isLasa: true,
    lasaConfusionWith: 'Celexa',
    lasaWarning: 'Do not confuse with Celexa (citalopram SSRI) or Cerebyx.',
  },
  {
    term: 'Citalopram',
    category: 'medication',
    normalized: 'citalopram',
    frequencyScore: 90,
    description: 'SSRI antidepressant for depression (monitor QTc prolongation)',
    brandNames: ['Celexa'],
    standardStrengths: ['10mg', '20mg', '40mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Celebrex',
    lasaWarning: 'Do not confuse with Celebrex (celecoxib NSAID).',
  },
  {
    term: 'Famotidine',
    category: 'medication',
    normalized: 'famotidine',
    frequencyScore: 94,
    description: 'H2 receptor antagonist for heartburn, peptic ulcer & stress ulcer prophylaxis',
    brandNames: ['Pepcid', 'Pepcid AC', 'Zantac 360'],
    standardStrengths: ['10mg', '20mg', '40mg', '40mg/5mL'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Cetirizine',
    category: 'medication',
    normalized: 'cetirizine',
    frequencyScore: 93,
    description: 'Second-generation piperazine antihistamine for allergic rhinitis & urticaria',
    brandNames: ['Zyrtec'],
    standardStrengths: ['5mg', '10mg', '5mg/5mL'],
    therapeuticClass: 'Respiratory',
    isLasa: true,
    lasaConfusionWith: 'Zantac',
    lasaWarning: 'Do not confuse with Zantac (H2RA).',
  },
  {
    term: 'Loratadine',
    category: 'medication',
    normalized: 'loratadine',
    frequencyScore: 92,
    description: 'Non-sedating second-generation H1 antihistamine',
    brandNames: ['Claritin', 'Alavert'],
    standardStrengths: ['10mg', '5mg/5mL'],
    therapeuticClass: 'Respiratory',
  },
  {
    term: 'Fexofenadine',
    category: 'medication',
    normalized: 'fexofenadine',
    frequencyScore: 88,
    description: 'Non-sedating selective peripheral H1 blocker for seasonal allergies',
    brandNames: ['Allegra'],
    standardStrengths: ['60mg', '180mg'],
    therapeuticClass: 'Respiratory',
  },
  {
    term: 'Allopurinol',
    category: 'medication',
    normalized: 'allopurinol',
    frequencyScore: 89,
    description: 'Xanthine oxidase inhibitor for chronic gout & tumor lysis hyperuricemia',
    brandNames: ['Zyloprim', 'Aloprim'],
    standardStrengths: ['100mg', '300mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Colchicine',
    category: 'medication',
    normalized: 'colchicine',
    frequencyScore: 82,
    description: 'Antimitotic tubulin inhibitor for acute gout flare treatment & prophylaxis',
    brandNames: ['Colcrys', 'Mitigare', 'Gloperba'],
    standardStrengths: ['0.6mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Spironolactone',
    category: 'medication',
    normalized: 'spironolactone',
    frequencyScore: 90,
    description: 'Potassium-sparing aldosterone antagonist diuretic for heart failure & ascites',
    brandNames: ['Aldactone', 'Carospir'],
    standardStrengths: ['25mg', '50mg', '100mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Finasteride',
    category: 'medication',
    normalized: 'finasteride',
    frequencyScore: 86,
    description: '5-alpha reductase inhibitor for benign prostatic hyperplasia (BPH) & alopecia',
    brandNames: ['Proscar', 'Propecia'],
    standardStrengths: ['1mg', '5mg'],
    therapeuticClass: 'Gastrointestinal & Urological',
  },
  {
    term: 'Tamsulosin',
    category: 'medication',
    normalized: 'tamsulosin',
    frequencyScore: 92,
    description: 'Selective alpha-1A adrenergic blocker for BPH urinary outflow obstruction',
    brandNames: ['Flomax'],
    standardStrengths: ['0.4mg'],
    therapeuticClass: 'Gastrointestinal & Urological',
  },
  {
    term: 'Baclofen',
    category: 'medication',
    normalized: 'baclofen',
    frequencyScore: 85,
    description: 'GABA-B agonist skeletal muscle relaxant for spasticity in MS & spinal injury',
    brandNames: ['Lioresal', 'Gablofen'],
    standardStrengths: ['5mg', '10mg', '20mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Cyclobenzaprine',
    category: 'medication',
    normalized: 'cyclobenzaprine',
    frequencyScore: 91,
    description: 'Central muscle relaxant for acute, painful musculoskeletal spasms',
    brandNames: ['Flexeril', 'Amrix', 'Fexmid'],
    standardStrengths: ['5mg', '7.5mg', '10mg', '15mg ER', '30mg ER'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Methocarbamol',
    category: 'medication',
    normalized: 'methocarbamol',
    frequencyScore: 84,
    description: 'Centrally-acting muscle relaxant for acute skeletal discomfort',
    brandNames: ['Robaxin'],
    standardStrengths: ['500mg', '750mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Carvedilol',
    category: 'medication',
    normalized: 'carvedilol',
    frequencyScore: 92,
    description: 'Non-selective beta and alpha-1 blocker for HFrEF & hypertension',
    brandNames: ['Coreg', 'Coreg CR'],
    standardStrengths: ['3.125mg', '6.25mg', '12.5mg', '25mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Atenolol',
    category: 'medication',
    normalized: 'atenolol',
    frequencyScore: 88,
    description: 'Beta-1 cardioselective adrenergic blocker for angina & post-MI',
    brandNames: ['Tenormin'],
    standardStrengths: ['25mg', '50mg', '100mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Propranolol',
    category: 'medication',
    normalized: 'propranolol',
    frequencyScore: 89,
    description: 'Non-selective beta blocker for essential tremor, performance anxiety & migraine',
    brandNames: ['Inderal', 'Inderal LA', 'InnoPran XL', 'Hemangeol'],
    standardStrengths: ['10mg', '20mg', '40mg', '60mg', '80mg', '120mg LA'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Venlafaxine',
    category: 'medication',
    normalized: 'venlafaxine',
    frequencyScore: 91,
    description: 'SNRI for major depression, panic disorder, social phobia & GAD',
    brandNames: ['Effexor', 'Effexor XR'],
    standardStrengths: ['25mg', '37.5mg', '75mg', '150mg', '225mg ER'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Bupropion Hydrochloride',
    category: 'medication',
    normalized: 'bupropionhydrochloride',
    frequencyScore: 94,
    description: 'Norepinephrine-dopamine reuptake inhibitor (NDRI) for depression & smoking cessation',
    brandNames: ['Wellbutrin', 'Wellbutrin SR', 'Wellbutrin XL', 'Zyban', 'Aplenzin'],
    standardStrengths: ['75mg', '100mg', '150mg SR', '200mg SR', '150mg XL', '300mg XL'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Fluoxetine',
    category: 'medication',
    normalized: 'fluoxetine',
    frequencyScore: 93,
    description: 'SSRI antidepressant for MDD, bulimia nervosa & panic disorder',
    brandNames: ['Prozac', 'Sarafem'],
    standardStrengths: ['10mg', '20mg', '40mg', '90mg weekly'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Paroxetine',
    category: 'medication',
    normalized: 'paroxetine',
    frequencyScore: 86,
    description: 'Potent SSRI for depression, OCD & social anxiety disorder',
    brandNames: ['Paxil', 'Paxil CR', 'Pexeva', 'Brisdelle'],
    standardStrengths: ['10mg', '20mg', '30mg', '40mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Mirtazapine',
    category: 'medication',
    normalized: 'mirtazapine',
    frequencyScore: 87,
    description: 'Alpha-2 antagonist antidepressant with appetite stimulating & sedating properties',
    brandNames: ['Remeron', 'Remeron SolTab'],
    standardStrengths: ['7.5mg', '15mg', '30mg', '45mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Quetiapine',
    category: 'medication',
    normalized: 'quetiapine',
    frequencyScore: 92,
    description: 'Atypical antipsychotic for schizophrenia, bipolar mania/depression & adjunct MDD',
    brandNames: ['Seroquel', 'Seroquel XR'],
    standardStrengths: ['25mg', '50mg', '100mg', '200mg', '300mg', '400mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Aripiprazole',
    category: 'medication',
    normalized: 'aripiprazole',
    frequencyScore: 91,
    description: 'D2 partial agonist atypical antipsychotic for schizophrenia & bipolar disorder',
    brandNames: ['Abilify', 'Abilify Maintena', 'Aristada'],
    standardStrengths: ['2mg', '5mg', '10mg', '15mg', '20mg', '30mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Risperidone',
    category: 'medication',
    normalized: 'risperidone',
    frequencyScore: 88,
    description: 'Second-generation antipsychotic for schizophrenia & bipolar mania',
    brandNames: ['Risperdal', 'Risperdal Consta', 'Perseris'],
    standardStrengths: ['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '1mg/mL'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Ropinirole',
    lasaWarning: 'Do not confuse with Ropinirole (dopamine agonist for Parkinson/RLS).',
  },
  {
    term: 'Ropinirole',
    category: 'medication',
    normalized: 'ropinirole',
    frequencyScore: 81,
    description: 'Non-ergoline dopamine D2/D3 agonist for Parkinson disease & restless legs syndrome',
    brandNames: ['Requip', 'Requip XL'],
    standardStrengths: ['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '4mg', '5mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Risperidone',
    lasaWarning: 'Do not confuse with Risperidone (antipsychotic).',
  },
  {
    term: 'Lamotrigine',
    category: 'medication',
    normalized: 'lamotrigine',
    frequencyScore: 90,
    description: 'Voltage-gated sodium channel blocker for epilepsy & bipolar I maintenance',
    brandNames: ['Lamictal', 'Lamictal XR', 'Lamictal ODT'],
    standardStrengths: ['25mg', '50mg', '100mg', '150mg', '200mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Lamivudine',
    lasaWarning: 'Do not confuse with Lamivudine (HIV/HBV antiviral) or Ludiomil.',
  },
  {
    term: 'Levetiracetam',
    category: 'medication',
    normalized: 'levetiracetam',
    frequencyScore: 89,
    description: 'SV2A vesicle protein modulator antiepileptic for focal and generalized seizures',
    brandNames: ['Keppra', 'Keppra XR', 'Roweepra'],
    standardStrengths: ['250mg', '500mg', '750mg', '1000mg', '100mg/mL'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Topiramate',
    category: 'medication',
    normalized: 'topiramate',
    frequencyScore: 87,
    description: 'Carbonic anhydrase inhibitor antiepileptic for seizure control & migraine prophylaxis',
    brandNames: ['Topamax', 'Trokendi XR', 'Qudexy XR'],
    standardStrengths: ['25mg', '50mg', '100mg', '200mg'],
    therapeuticClass: 'Central Nervous System',
    isLasa: true,
    lasaConfusionWith: 'Toprol XL',
    lasaWarning: 'Do not confuse with Toprol XL (metoprolol succinate).',
  },
  {
    term: 'Oxcarbazepine',
    category: 'medication',
    normalized: 'oxcarbazepine',
    frequencyScore: 82,
    description: 'Voltage-sensitive sodium channel blocker for partial seizures',
    brandNames: ['Trileptal', 'Oxtellar XR'],
    standardStrengths: ['150mg', '300mg', '600mg', '300mg/5mL'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Divalproex Sodium',
    category: 'medication',
    normalized: 'divalproexsodium',
    frequencyScore: 85,
    description: 'Valproate compound for complex partial seizures, bipolar mania & migraine prevention',
    brandNames: ['Depakote', 'Depakote ER', 'Depakote Sprinkles'],
    standardStrengths: ['125mg', '250mg', '500mg'],
    therapeuticClass: 'Central Nervous System',
  },
  {
    term: 'Empagliflozin',
    category: 'medication',
    normalized: 'empagliflozin',
    frequencyScore: 92,
    description: 'SGLT2 inhibitor for type 2 diabetes, heart failure (HFrEF/HFpEF) & CKD progression',
    brandNames: ['Jardiance'],
    standardStrengths: ['10mg', '25mg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Dapagliflozin',
    category: 'medication',
    normalized: 'dapagliflozin',
    frequencyScore: 90,
    description: 'SGLT2 inhibitor for glycemic control, heart failure & chronic kidney disease',
    brandNames: ['Farxiga'],
    standardStrengths: ['5mg', '10mg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Semaglutide',
    category: 'medication',
    normalized: 'semaglutide',
    frequencyScore: 98,
    description: 'GLP-1 receptor agonist for type 2 diabetes glycemic control & chronic weight management',
    brandNames: ['Ozempic', 'Wegovy', 'Rybelsus'],
    standardStrengths: ['0.25mg', '0.5mg', '1mg', '2mg', '3mg', '7mg', '14mg', '2.4mg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Dulaglutide',
    category: 'medication',
    normalized: 'dulaglutide',
    frequencyScore: 91,
    description: 'Once-weekly GLP-1 receptor agonist for type 2 diabetes',
    brandNames: ['Trulicity'],
    standardStrengths: ['0.75mg/0.5mL', '1.5mg/0.5mL', '3mg/0.5mL', '4.5mg/0.5mL'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Tirzepatide',
    category: 'medication',
    normalized: 'tirzepatide',
    frequencyScore: 96,
    description: 'Dual GIP and GLP-1 receptor agonist for type 2 diabetes & obesity',
    brandNames: ['Mounjaro', 'Zepbound'],
    standardStrengths: ['2.5mg', '5mg', '7.5mg', '10mg', '12.5mg', '15mg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Insulin Glargine',
    category: 'medication',
    normalized: 'insulinglargine',
    frequencyScore: 95,
    description: 'Long-acting peakless basal insulin analog for diabetes mellitus',
    brandNames: ['Lantus', 'Basaglar', 'Toujeo', 'Semglee'],
    standardStrengths: ['100 units/mL (U-100)', '300 units/mL (U-300)'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Insulin Lispro',
    category: 'medication',
    normalized: 'insulinlispro',
    frequencyScore: 92,
    description: 'Rapid-acting mealtime insulin analog (inject within 15 min of meal)',
    brandNames: ['Humalog', 'Admelog', 'Lyumjev'],
    standardStrengths: ['100 units/mL (U-100)', '200 units/mL (U-200)'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Insulin Aspart',
    category: 'medication',
    normalized: 'insulinaspart',
    frequencyScore: 93,
    description: 'Rapid-acting prandial human insulin analog for postprandial glycemic coverage',
    brandNames: ['Novolog', 'Fiasp'],
    standardStrengths: ['100 units/mL (U-100)'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Insulin Detemir',
    category: 'medication',
    normalized: 'insulindetemir',
    frequencyScore: 86,
    description: 'Intermediate to long-acting basal insulin analog',
    brandNames: ['Levemir'],
    standardStrengths: ['100 units/mL (U-100)'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Glimepiride',
    category: 'medication',
    normalized: 'glimepiride',
    frequencyScore: 89,
    description: 'Second-generation sulfonylurea secretagogue for type 2 diabetes',
    brandNames: ['Amaryl'],
    standardStrengths: ['1mg', '2mg', '4mg'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Glipizide',
    category: 'medication',
    normalized: 'glipizide',
    frequencyScore: 91,
    description: 'Second-generation sulfonylurea for glycemic control in T2D',
    brandNames: ['Glucotrol', 'Glucotrol XL'],
    standardStrengths: ['5mg', '10mg', '2.5mg XL', '5mg XL', '10mg XL'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Apixaban',
    category: 'medication',
    normalized: 'apixaban',
    frequencyScore: 98,
    description: 'Direct factor Xa inhibitor DOAC for non-valvular AFib stroke prevention & DVT/PE',
    brandNames: ['Eliquis'],
    standardStrengths: ['2.5mg', '5mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Rivaroxaban',
    category: 'medication',
    normalized: 'rivaroxaban',
    frequencyScore: 93,
    description: 'Direct factor Xa inhibitor DOAC for thromboembolism & CAD/PAD',
    brandNames: ['Xarelto'],
    standardStrengths: ['2.5mg', '10mg', '15mg', '20mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Dabigatran Etexilate',
    category: 'medication',
    normalized: 'dabigatranetexilate',
    frequencyScore: 83,
    description: 'Direct thrombin (Factor IIa) inhibitor DOAC for AFib thromboembolism',
    brandNames: ['Pradaxa'],
    standardStrengths: ['75mg', '110mg', '150mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Enoxaparin Sodium',
    category: 'medication',
    normalized: 'enoxaparinsodium',
    frequencyScore: 89,
    description: 'Low-molecular-weight heparin (LMWH) for DVT prophylaxis & bridging anticoagulation',
    brandNames: ['Lovenox'],
    standardStrengths: ['30mg/0.3mL', '40mg/0.4mL', '60mg/0.6mL', '80mg/0.8mL', '100mg/1mL', '120mg/0.8mL', '150mg/1mL'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Heparin Sodium',
    category: 'medication',
    normalized: 'heparinsodium',
    frequencyScore: 90,
    description: 'Unfractionated heparin for acute thrombosis & cardiopulmonary bypass',
    brandNames: ['Hep-Lock'],
    standardStrengths: ['1000 units/mL', '5000 units/mL', '10000 units/mL', '25000 units/500mL'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Valsartan',
    category: 'medication',
    normalized: 'valsartan',
    frequencyScore: 91,
    description: 'Angiotensin II receptor antagonist for hypertension & post-MI survival',
    brandNames: ['Diovan'],
    standardStrengths: ['40mg', '80mg', '160mg', '320mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Sacubitril / Valsartan',
    category: 'medication',
    normalized: 'sacubitrilvalsartan',
    frequencyScore: 92,
    description: 'Angiotensin receptor-neprilysin inhibitor (ARNI) for chronic HFrEF & HFpEF',
    brandNames: ['Entresto'],
    standardStrengths: ['24/26mg', '49/51mg', '97/103mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Enalapril',
    category: 'medication',
    normalized: 'enalapril',
    frequencyScore: 87,
    description: 'Prodrug ACE inhibitor for hypertension & asymptomatic left ventricular dysfunction',
    brandNames: ['Vasotec', 'Epaned'],
    standardStrengths: ['2.5mg', '5mg', '10mg', '20mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Ramipril',
    category: 'medication',
    normalized: 'ramipril',
    frequencyScore: 88,
    description: 'Tissue-specific ACE inhibitor for hypertension & CV mortality risk reduction',
    brandNames: ['Altace'],
    standardStrengths: ['1.25mg', '2.5mg', '5mg', '10mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Benazepril',
    category: 'medication',
    normalized: 'benazepril',
    frequencyScore: 84,
    description: 'ACE inhibitor for hypertension',
    brandNames: ['Lotensin'],
    standardStrengths: ['5mg', '10mg', '20mg', '40mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Irbesartan',
    category: 'medication',
    normalized: 'irbesartan',
    frequencyScore: 86,
    description: 'ARB for hypertension and type 2 diabetic nephropathy',
    brandNames: ['Avapro'],
    standardStrengths: ['75mg', '150mg', '300mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Olmesartan Medoxomil',
    category: 'medication',
    normalized: 'olmesartanmedoxomil',
    frequencyScore: 87,
    description: 'ARB for hypertension',
    brandNames: ['Benicar'],
    standardStrengths: ['5mg', '20mg', '40mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Diltiazem Hydrochloride',
    category: 'medication',
    normalized: 'diltiazemhydrochloride',
    frequencyScore: 91,
    description: 'Non-dihydropyridine calcium channel blocker for AFib rate control & angina',
    brandNames: ['Cardizem', 'Cardizem CD', 'Tiazac', 'Cartia XT', 'Dilacor XR'],
    standardStrengths: ['30mg', '60mg', '90mg', '120mg', '180mg CD', '240mg CD', '300mg CD', '360mg CD'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Verapamil Hydrochloride',
    category: 'medication',
    normalized: 'verapamilhydrochloride',
    frequencyScore: 85,
    description: 'Phenylalkylamine non-DHP CCB for PSVT, cluster headache prophylaxis & rate control',
    brandNames: ['Calan', 'Calan SR', 'Verelan', 'Covera-HS'],
    standardStrengths: ['40mg', '80mg', '120mg', '180mg SR', '240mg SR'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Digoxin',
    category: 'medication',
    normalized: 'digoxin',
    frequencyScore: 83,
    description: 'Cardiac glycoside Na+/K+ ATPase inhibitor for systolic heart failure & AFib rate control',
    brandNames: ['Lanoxin', 'Digox'],
    standardStrengths: ['0.0625mg', '0.125mg', '0.25mg', '0.05mg/mL'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Amiodarone Hydrochloride',
    category: 'medication',
    normalized: 'amiodaronehydrochloride',
    frequencyScore: 87,
    description: 'Class III antiarrhythmic for ventricular tachycardia, VFib & refractory AFib',
    brandNames: ['Cordarone', 'Pacerone', 'Nexterone'],
    standardStrengths: ['100mg', '200mg', '400mg', '150mg/3mL IV'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Nitroglycerin',
    category: 'medication',
    normalized: 'nitroglycerin',
    frequencyScore: 90,
    description: 'Nitrate coronary vasodilator for acute angina pectoris relief (SL 0.4mg PRN)',
    brandNames: ['Nitrostat', 'Nitro-Dur', 'Nitro-Bid', 'Nitrolingual'],
    standardStrengths: ['0.4mg SL', '0.3mg SL', '0.6mg SL', '0.2mg/hr patch', '0.4mg/hr patch', '0.6mg/hr patch'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Isosorbide Mononitrate',
    category: 'medication',
    normalized: 'isosorbidemononitrate',
    frequencyScore: 87,
    description: 'Long-acting organic nitrate for chronic angina prophylaxis',
    brandNames: ['Imdur', 'Monoket', 'Ismo'],
    standardStrengths: ['30mg ER', '60mg ER', '120mg ER', '10mg', '20mg'],
    therapeuticClass: 'Cardiovascular',
  },
  {
    term: 'Ranitidine',
    category: 'medication',
    normalized: 'ranitidine',
    frequencyScore: 70,
    description: 'Historical H2 receptor antagonist (largely replaced by famotidine)',
    brandNames: ['Zantac'],
    standardStrengths: ['75mg', '150mg', '300mg'],
    therapeuticClass: 'Gastrointestinal',
    isLasa: true,
    lasaConfusionWith: 'Zyrtec',
    lasaWarning: 'Do not confuse with Zyrtec (cetirizine antihistamine).',
  },
  {
    term: 'Lansoprazole',
    category: 'medication',
    normalized: 'lansoprazole',
    frequencyScore: 88,
    description: 'Proton Pump Inhibitor for gastric ulcer healing & H. pylori eradication',
    brandNames: ['Prevacid', 'Prevacid SoluTab'],
    standardStrengths: ['15mg', '30mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Esomeprazole',
    category: 'medication',
    normalized: 'esomeprazole',
    frequencyScore: 91,
    description: 'S-enantiomer of omeprazole PPI for severe erosive esophagitis & GERD',
    brandNames: ['Nexium', 'Nexium 24HR'],
    standardStrengths: ['20mg', '40mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Rabeprazole Sodium',
    category: 'medication',
    normalized: 'rabeprazolesodium',
    frequencyScore: 80,
    description: 'Proton Pump Inhibitor for duodenal ulcers & pathological hypersecretion',
    brandNames: ['Aciphex'],
    standardStrengths: ['20mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Sucralfate',
    category: 'medication',
    normalized: 'sucralfate',
    frequencyScore: 84,
    description: 'Basic aluminum sucrose complex cytoprotective agent for active duodenal ulcers',
    brandNames: ['Carafate'],
    standardStrengths: ['1g', '1g/10mL susp'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Dicyclomine Hydrochloride',
    category: 'medication',
    normalized: 'dicyclominehydrochloride',
    frequencyScore: 87,
    description: 'Antispasmodic anticholinergic for irritable bowel syndrome (IBS) cramping',
    brandNames: ['Bentyl'],
    standardStrengths: ['10mg', '20mg', '10mg/5mL'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Ondansetron Hydrochloride',
    category: 'medication',
    normalized: 'ondansetronhydrochloride',
    frequencyScore: 96,
    description: '5-HT3 receptor antagonist antiemetic for chemotherapy, post-op nausea & gastroenteritis',
    brandNames: ['Zofran', 'Zofran ODT', 'Zuplenz'],
    standardStrengths: ['4mg', '8mg', '4mg ODT', '8mg ODT', '4mg/2mL IV', '4mg/5mL'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Promethazine Hydrochloride',
    category: 'medication',
    normalized: 'promethazinehydrochloride',
    frequencyScore: 89,
    description: 'Phenothiazine derivative H1 antagonist antiemetic & sedative',
    brandNames: ['Phenergan', 'Promethegan'],
    standardStrengths: ['12.5mg', '25mg', '50mg', '25mg/mL IV/IM'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Metoclopramide Hydrochloride',
    category: 'medication',
    normalized: 'metoclopramidehydrochloride',
    frequencyScore: 86,
    description: 'D2 antagonist prokinetic agent for diabetic gastroparesis & intractable nausea',
    brandNames: ['Reglan', 'Gimoti'],
    standardStrengths: ['5mg', '10mg', '5mg/5mL'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Polyethylene Glycol 3350',
    category: 'medication',
    normalized: 'polyethyleneglycol3350',
    frequencyScore: 94,
    description: 'Osmotic laxative for constipation & bowel preparation',
    brandNames: ['MiraLAX', 'GaviLAX', 'GlycoLax'],
    standardStrengths: ['17g/dose powder'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Docusate Sodium',
    category: 'medication',
    normalized: 'docusatesodium',
    frequencyScore: 92,
    description: 'Anionic surfactant stool softener for constipation prevention',
    brandNames: ['Colace', 'Surfak'],
    standardStrengths: ['50mg', '100mg', '250mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Senna',
    category: 'medication',
    normalized: 'senna',
    frequencyScore: 88,
    description: 'Anthraquinone stimulant laxative',
    brandNames: ['Senokot', 'Ex-Lax'],
    standardStrengths: ['8.6mg', '17.2mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Bisacodyl',
    category: 'medication',
    normalized: 'bisacodyl',
    frequencyScore: 86,
    description: 'Diphenylmethane stimulant laxative for acute bowel evacuation',
    brandNames: ['Dulcolax'],
    standardStrengths: ['5mg tablet', '10mg suppository'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Loperamide Hydrochloride',
    category: 'medication',
    normalized: 'loperamidehydrochloride',
    frequencyScore: 89,
    description: 'Peripheral opioid mu-receptor agonist antidiarrheal',
    brandNames: ['Imodium A-D'],
    standardStrengths: ['2mg cap', '1mg/7.5mL'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Diphenoxylate / Atropine',
    category: 'medication',
    normalized: 'diphenoxylateatropine',
    frequencyScore: 80,
    description: 'Schedule V antidiarrheal combination',
    brandNames: ['Lomotil'],
    standardStrengths: ['2.5/0.025mg'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Mesalamine',
    category: 'medication',
    normalized: 'mesalamine',
    frequencyScore: 84,
    description: '5-aminosalicylic acid (5-ASA) anti-inflammatory for ulcerative colitis induction & remission',
    brandNames: ['Asacol HD', 'Lialda', 'Pentasa', 'Apriso', 'Canasa', 'Rowasa'],
    standardStrengths: ['400mg', '800mg', '1.2g', '1000mg supp'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Budesonide',
    category: 'medication',
    normalized: 'budesonide',
    frequencyScore: 89,
    description: 'Locally-acting high first-pass corticosteroid for Crohn disease & asthma maintenance',
    brandNames: ['Entocort EC', 'Uceris', 'Pulmicort', 'Pulmicort Flexhaler'],
    standardStrengths: ['3mg EC cap', '9mg ER tab', '0.25mg/2mL neb', '0.5mg/2mL neb', '180mcg inhaler'],
    therapeuticClass: 'Gastrointestinal',
  },
  {
    term: 'Hydrocortisone',
    category: 'medication',
    normalized: 'hydrocortisone',
    frequencyScore: 92,
    description: 'Short-acting glucocorticoid for adrenal insufficiency & inflammatory dermatoses',
    brandNames: ['Cortef', 'Solu-Cortef', 'Anusol-HC', 'Cortaid'],
    standardStrengths: ['5mg', '10mg', '20mg', '100mg IV', '1% cream', '2.5% cream'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Methylprednisolone',
    category: 'medication',
    normalized: 'methylprednisolone',
    frequencyScore: 93,
    description: 'Intermediate-acting glucocorticoid for acute allergic reactions & COPD exacerbations',
    brandNames: ['Medrol', 'Medrol Dosepak', 'Solu-Medrol', 'Depo-Medrol'],
    standardStrengths: ['4mg Dosepak', '8mg', '16mg', '40mg IV', '125mg IV', '1g IV'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Dexamethasone',
    category: 'medication',
    normalized: 'dexamethasone',
    frequencyScore: 94,
    description: 'Long-acting high-potency fluorinated corticosteroid for cerebral edema & COVID-19 CAP',
    brandNames: ['Decadron', 'DexPak'],
    standardStrengths: ['0.5mg', '0.75mg', '1.5mg', '4mg', '6mg', '4mg/mL IV'],
    therapeuticClass: 'Endocrine & Diabetes',
  },
  {
    term: 'Methotrexate',
    category: 'medication',
    normalized: 'methotrexate',
    frequencyScore: 87,
    description: 'Antifolate DMARD for rheumatoid arthritis, psoriasis & oncology (ONCE WEEKLY DOSING)',
    brandNames: ['Trexall', 'Otrexup', 'Rasuvo'],
    standardStrengths: ['2.5mg (take once weekly)', '5mg', '10mg', '15mg', '20mg', '25mg/mL'],
    therapeuticClass: 'Analgesics & Opioids',
    isLasa: true,
    lasaConfusionWith: 'Metolazone',
    lasaWarning: 'High Risk: Dose once WEEKLY for non-oncologic indications, never daily!',
  },
  {
    term: 'Hydroxychloroquine Sulfate',
    category: 'medication',
    normalized: 'hydroxychloroquinesulfate',
    frequencyScore: 89,
    description: 'Aminoquinoline DMARD for systemic lupus erythematosus (SLE) & rheumatoid arthritis',
    brandNames: ['Plaquenil'],
    standardStrengths: ['200mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Sulfasalazine',
    category: 'medication',
    normalized: 'sulfasalazine',
    frequencyScore: 83,
    description: '5-ASA / sulfapyridine conjugate for rheumatoid arthritis & inflammatory bowel disease',
    brandNames: ['Azulfidine', 'Azulfidine EN-tabs'],
    standardStrengths: ['500mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Azathioprine',
    category: 'medication',
    normalized: 'azathioprine',
    frequencyScore: 82,
    description: 'Purine antimetabolite immunosuppressant for kidney transplant & severe autoimmune flares',
    brandNames: ['Imuran', 'Azasan'],
    standardStrengths: ['50mg', '75mg', '100mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Mycophenolate Mofetil',
    category: 'medication',
    normalized: 'mycophenolatemofetil',
    frequencyScore: 84,
    description: 'IMPDH inhibitor immunosuppressant for organ rejection prophylaxis & lupus nephritis',
    brandNames: ['CellCept'],
    standardStrengths: ['250mg', '500mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Tacrolimus',
    category: 'medication',
    normalized: 'tacrolimus',
    frequencyScore: 86,
    description: 'Calcineurin inhibitor immunosuppressant (FK506) for solid organ transplant',
    brandNames: ['Prograf', 'Astagraf XL', 'Envarsus XR', 'Protopic'],
    standardStrengths: ['0.5mg', '1mg', '5mg', '0.03% oint', '0.1% oint'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Cyclosporine',
    category: 'medication',
    normalized: 'cyclosporine',
    frequencyScore: 83,
    description: 'Calcineurin inhibitor for transplant rejection & severe refractory psoriasis',
    brandNames: ['Neoral', 'Sandimmune', 'Gengraf', 'Restasis'],
    standardStrengths: ['25mg', '50mg', '100mg', '0.05% eye drops'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Levofloxacin',
    category: 'medication',
    normalized: 'levofloxacin',
    frequencyScore: 89,
    description: 'Respiratory fluoroquinolone for community-acquired pneumonia & pyelonephritis',
    brandNames: ['Levaquin'],
    standardStrengths: ['250mg', '500mg', '750mg', '500mg/20mL IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Moxifloxacin Hydrochloride',
    category: 'medication',
    normalized: 'moxifloxacinhydrochloride',
    frequencyScore: 83,
    description: '4th generation fluoroquinolone with enhanced Gram-positive and anaerobic coverage',
    brandNames: ['Avelox', 'Vigamox'],
    standardStrengths: ['400mg', '0.5% eye drops'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Vancomycin Hydrochloride',
    category: 'medication',
    normalized: 'vancomycinhydrochloride',
    frequencyScore: 92,
    description: 'Glycopeptide antibiotic for MRSA bacteremia (IV) and C. difficile enterocolitis (Oral only)',
    brandNames: ['Vancocin', 'Firvanq'],
    standardStrengths: ['125mg PO', '250mg PO', '500mg IV', '1g IV', '1.5g IV', '1.75g IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Linezolid',
    category: 'medication',
    normalized: 'linezolid',
    frequencyScore: 82,
    description: 'Oxazolidinone antibiotic for VRE and MRSA pneumonia (monitor for serotonin syndrome & myelosuppression)',
    brandNames: ['Zyvox'],
    standardStrengths: ['600mg PO/IV', '100mg/5mL'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Daptomycin',
    category: 'medication',
    normalized: 'daptomycin',
    frequencyScore: 81,
    description: 'Lipopeptide antibiotic for complicated skin infections & MRSA bacteremia (inactivated by lung surfactant)',
    brandNames: ['Cubicin', 'Cubicin RF'],
    standardStrengths: ['500mg IV vial'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Piperacillin / Tazobactam',
    category: 'medication',
    normalized: 'piperacillintazobactam',
    frequencyScore: 91,
    description: 'Broad-spectrum antipseudomonal penicillin / beta-lactamase inhibitor (Zosyn)',
    brandNames: ['Zosyn'],
    standardStrengths: ['2.25g IV', '3.375g IV', '4.5g IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Ceftriaxone Sodium',
    category: 'medication',
    normalized: 'ceftriaxonesodium',
    frequencyScore: 94,
    description: 'Third-generation cephalosporin for CAP, bacterial meningitis & gonorrhea',
    brandNames: ['Rocephin'],
    standardStrengths: ['250mg IM', '500mg IM', '1g IV/IM', '2g IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Cefepime Hydrochloride',
    category: 'medication',
    normalized: 'cefepimehydrochloride',
    frequencyScore: 88,
    description: 'Fourth-generation antipseudomonal cephalosporin for neutropenic fever & nosocomial infections',
    brandNames: ['Maxipime'],
    standardStrengths: ['1g IV', '2g IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Meropenem',
    category: 'medication',
    normalized: 'meropenem',
    frequencyScore: 88,
    description: 'Ultra broad-spectrum carbapenem for multidrug-resistant intra-abdominal infections & ESBL',
    brandNames: ['Merrem'],
    standardStrengths: ['500mg IV', '1g IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Clindamycin Hydrochloride',
    category: 'medication',
    normalized: 'clindamycinhydrochloride',
    frequencyScore: 90,
    description: 'Lincosamide antibiotic for anaerobic, dental, & toxin-mediated Gram-positive infections',
    brandNames: ['Cleocin', 'Cleocin T'],
    standardStrengths: ['150mg', '300mg', '450mg', '600mg IV', '900mg IV', '1% topical'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Trimethoprim / Sulfamethoxazole',
    category: 'medication',
    normalized: 'trimethoprimsulfamethoxazole',
    frequencyScore: 93,
    description: 'Folate synthesis inhibitor antibacterial (TMP-SMX / Bactrim DS) for UTI, MRSA & PCP',
    brandNames: ['Bactrim', 'Bactrim DS', 'Septra DS'],
    standardStrengths: ['80/400mg (SS)', '160/800mg (DS)'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Nitrofurantoin Monohydrate',
    category: 'medication',
    normalized: 'nitrofurantoinmonohydrate',
    frequencyScore: 92,
    description: 'Urinary tract antiseptic antibiotic for acute uncomplicated cystitis (Macrobid)',
    brandNames: ['Macrobid', 'Macrodantin', 'Furadantin'],
    standardStrengths: ['100mg BID', '50mg QID'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Fluconazole',
    category: 'medication',
    normalized: 'fluconazole',
    frequencyScore: 92,
    description: 'Triazole antifungal for vulvovaginal candidiasis (150mg x1) & systemic cryptococcosis',
    brandNames: ['Diflucan'],
    standardStrengths: ['50mg', '100mg', '150mg', '200mg', '400mg IV', '10mg/mL'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Nystatin',
    category: 'medication',
    normalized: 'nystatin',
    frequencyScore: 89,
    description: 'Polyene antifungal for oral candidiasis (swish and swallow) & cutaneous intertrigo',
    brandNames: ['Mycostatin', 'Nyamyc', 'Nystop'],
    standardStrengths: ['100000 units/mL oral susp', '100000 units/g cream/powder'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Acyclovir',
    category: 'medication',
    normalized: 'acyclovir',
    frequencyScore: 88,
    description: 'Guanosine analog antiviral for HSV-1, HSV-2 & varicella zoster virus (VZV)',
    brandNames: ['Zovirax', 'Sitavig'],
    standardStrengths: ['200mg', '400mg', '800mg', '5% oint', '500mg IV'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Valacyclovir Hydrochloride',
    category: 'medication',
    normalized: 'valacyclovirhydrochloride',
    frequencyScore: 92,
    description: 'L-valyl ester prodrug of acyclovir for herpes zoster (shingles) & genital herpes',
    brandNames: ['Valtrex'],
    standardStrengths: ['500mg', '1000mg (1g)'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Oseltamivir Phosphate',
    category: 'medication',
    normalized: 'oseltamivirphosphate',
    frequencyScore: 91,
    description: 'Neuraminidase inhibitor for acute influenza A & B treatment (75mg PO BID x 5 days)',
    brandNames: ['Tamiflu'],
    standardStrengths: ['30mg', '45mg', '75mg', '6mg/mL susp'],
    therapeuticClass: 'Antibiotics',
  },
  {
    term: 'Ketorolac Tromethamine',
    category: 'medication',
    normalized: 'ketorolactromethamine',
    frequencyScore: 90,
    description: 'Potent IV/IM/oral NSAID for short-term moderate to severe acute pain (max 5 days)',
    brandNames: ['Toradol', 'Sprix'],
    standardStrengths: ['10mg PO', '15mg/mL IV', '30mg/mL IV/IM', '60mg/2mL IM'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Meloxicam',
    category: 'medication',
    normalized: 'meloxicam',
    frequencyScore: 93,
    description: 'Preferential COX-2 inhibitor NSAID for osteoarthritis & rheumatoid arthritis relief',
    brandNames: ['Mobic', 'Vivlodex', 'Anjeso'],
    standardStrengths: ['7.5mg', '15mg'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Naproxen',
    category: 'medication',
    normalized: 'naproxen',
    frequencyScore: 94,
    description: 'Non-selective NSAID with long half-life for acute gout, bursitis & dysmenorrhea',
    brandNames: ['Aleve', 'Naprosyn', 'Anaprox DS'],
    standardStrengths: ['220mg', '250mg', '375mg', '500mg', '550mg DS'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Diclofenac Sodium',
    category: 'medication',
    normalized: 'diclofenacsodium',
    frequencyScore: 91,
    description: 'NSAID topical gel and oral tablets for localized osteoarthritis & acute pain',
    brandNames: ['Voltaren', 'Voltaren Arthritis Pain Gel', 'Cataflam', 'Zipsor', 'Cambia'],
    standardStrengths: ['1% topical gel', '25mg', '50mg', '75mg', '100mg ER'],
    therapeuticClass: 'Analgesics & Opioids',
  },
  {
    term: 'Indomethacin',
    category: 'medication',
    normalized: 'indomethacin',
    frequencyScore: 84,
    description: 'Potent non-selective NSAID for acute gout flares, ankylosing spondylitis & pericarditis',
    brandNames: ['Indocin', 'Tivorbex'],
    standardStrengths: ['25mg', '50mg', '75mg ER', '50mg supp'],
    therapeuticClass: 'Analgesics & Opioids',
  },
];

// 2. Standard Clinical Dosages (50+ items)
const CLINICAL_DOSAGES: MedicalLexiconEntry[] = [
  { term: '0.25mg', category: 'dosage', normalized: '0.25mg', frequencyScore: 78, description: 'Dosage: 0.25 milligrams (250 mcg)' },
  { term: '0.5mg', category: 'dosage', normalized: '0.5mg', frequencyScore: 88, description: 'Dosage: 0.5 milligrams (500 mcg)' },
  { term: '1mg', category: 'dosage', normalized: '1mg', frequencyScore: 92, description: 'Dosage: 1 milligram' },
  { term: '2mg', category: 'dosage', normalized: '2mg', frequencyScore: 89, description: 'Dosage: 2 milligrams' },
  { term: '2.5mg', category: 'dosage', normalized: '2.5mg', frequencyScore: 86, description: 'Dosage: 2.5 milligrams' },
  { term: '3mg', category: 'dosage', normalized: '3mg', frequencyScore: 75, description: 'Dosage: 3 milligrams' },
  { term: '4mg', category: 'dosage', normalized: '4mg', frequencyScore: 85, description: 'Dosage: 4 milligrams' },
  { term: '5mg', category: 'dosage', normalized: '5mg', frequencyScore: 98, description: 'Dosage: 5 milligrams' },
  { term: '6.25mg', category: 'dosage', normalized: '6.25mg', frequencyScore: 78, description: 'Dosage: 6.25 milligrams' },
  { term: '7.5mg', category: 'dosage', normalized: '7.5mg', frequencyScore: 80, description: 'Dosage: 7.5 milligrams' },
  { term: '10mg', category: 'dosage', normalized: '10mg', frequencyScore: 99, description: 'Dosage: 10 milligrams' },
  { term: '12.5mg', category: 'dosage', normalized: '12.5mg', frequencyScore: 89, description: 'Dosage: 12.5 milligrams' },
  { term: '15mg', category: 'dosage', normalized: '15mg', frequencyScore: 82, description: 'Dosage: 15 milligrams' },
  { term: '20mg', category: 'dosage', normalized: '20mg', frequencyScore: 99, description: 'Dosage: 20 milligrams' },
  { term: '25mg', category: 'dosage', normalized: '25mg', frequencyScore: 95, description: 'Dosage: 25 milligrams' },
  { term: '30mg', category: 'dosage', normalized: '30mg', frequencyScore: 84, description: 'Dosage: 30 milligrams' },
  { term: '37.5mg', category: 'dosage', normalized: '37.5mg', frequencyScore: 77, description: 'Dosage: 37.5 milligrams' },
  { term: '40mg', category: 'dosage', normalized: '40mg', frequencyScore: 96, description: 'Dosage: 40 milligrams' },
  { term: '50mg', category: 'dosage', normalized: '50mg', frequencyScore: 99, description: 'Dosage: 50 milligrams' },
  { term: '60mg', category: 'dosage', normalized: '60mg', frequencyScore: 82, description: 'Dosage: 60 milligrams' },
  { term: '75mg', category: 'dosage', normalized: '75mg', frequencyScore: 88, description: 'Dosage: 75 milligrams' },
  { term: '80mg', category: 'dosage', normalized: '80mg', frequencyScore: 89, description: 'Dosage: 80 milligrams' },
  { term: '100mg', category: 'dosage', normalized: '100mg', frequencyScore: 99, description: 'Dosage: 100 milligrams' },
  { term: '125mg', category: 'dosage', normalized: '125mg', frequencyScore: 84, description: 'Dosage: 125 milligrams' },
  { term: '150mg', category: 'dosage', normalized: '150mg', frequencyScore: 87, description: 'Dosage: 150 milligrams' },
  { term: '200mg', category: 'dosage', normalized: '200mg', frequencyScore: 95, description: 'Dosage: 200 milligrams' },
  { term: '250mg', category: 'dosage', normalized: '250mg', frequencyScore: 97, description: 'Dosage: 250 milligrams' },
  { term: '300mg', category: 'dosage', normalized: '300mg', frequencyScore: 90, description: 'Dosage: 300 milligrams' },
  { term: '325mg', category: 'dosage', normalized: '325mg', frequencyScore: 92, description: 'Dosage: 325 milligrams (standard aspirin/APAP)' },
  { term: '400mg', category: 'dosage', normalized: '400mg', frequencyScore: 92, description: 'Dosage: 400 milligrams' },
  { term: '500mg', category: 'dosage', normalized: '500mg', frequencyScore: 99, description: 'Dosage: 500 milligrams' },
  { term: '600mg', category: 'dosage', normalized: '600mg', frequencyScore: 91, description: 'Dosage: 600 milligrams' },
  { term: '650mg', category: 'dosage', normalized: '650mg', frequencyScore: 86, description: 'Dosage: 650 milligrams (2 x 325mg)' },
  { term: '750mg', category: 'dosage', normalized: '750mg', frequencyScore: 86, description: 'Dosage: 750 milligrams' },
  { term: '800mg', category: 'dosage', normalized: '800mg', frequencyScore: 91, description: 'Dosage: 800 milligrams' },
  { term: '875mg', category: 'dosage', normalized: '875mg', frequencyScore: 90, description: 'Dosage: 875 milligrams (Amoxil high dose)' },
  { term: '1000mg', category: 'dosage', normalized: '1000mg', frequencyScore: 93, description: 'Dosage: 1000 milligrams (1 gram)' },
  { term: '1g', category: 'dosage', normalized: '1g', frequencyScore: 94, description: 'Dosage: 1 gram' },
  { term: '2g', category: 'dosage', normalized: '2g', frequencyScore: 85, description: 'Dosage: 2 grams' },
  { term: '25mcg', category: 'dosage', normalized: '25mcg', frequencyScore: 82, description: 'Dosage: 25 micrograms' },
  { term: '50mcg', category: 'dosage', normalized: '50mcg', frequencyScore: 87, description: 'Dosage: 50 micrograms' },
  { term: '75mcg', category: 'dosage', normalized: '75mcg', frequencyScore: 83, description: 'Dosage: 75 micrograms' },
  { term: '100mcg', category: 'dosage', normalized: '100mcg', frequencyScore: 88, description: 'Dosage: 100 micrograms' },
  { term: '125mcg', category: 'dosage', normalized: '125mcg', frequencyScore: 84, description: 'Dosage: 125 micrograms' },
  { term: '5mL', category: 'dosage', normalized: '5ml', frequencyScore: 90, description: 'Liquid volume: 5 milliliters (1 teaspoon / 1 tsp)' },
  { term: '10mL', category: 'dosage', normalized: '10ml', frequencyScore: 86, description: 'Liquid volume: 10 milliliters (2 teaspoons / 2 tsp)' },
  { term: '15mL', category: 'dosage', normalized: '15ml', frequencyScore: 88, description: 'Liquid volume: 15 milliliters (1 tablespoon / 1 tbsp)' },
  { term: '30mL', category: 'dosage', normalized: '30ml', frequencyScore: 82, description: 'Liquid volume: 30 milliliters (1 fluid ounce / 1 fl oz)' },
  { term: '125mg/5mL', category: 'dosage', normalized: '125mg5ml', frequencyScore: 88, description: 'Pediatric suspension concentration: 125mg per 5mL' },
  { term: '250mg/5mL', category: 'dosage', normalized: '250mg5ml', frequencyScore: 91, description: 'Pediatric suspension concentration: 250mg per 5mL' },
  { term: '1 puff', category: 'dosage', normalized: '1puff', frequencyScore: 88, description: 'Inhalation dose: 1 actuation' },
  { term: '2 puffs', category: 'dosage', normalized: '2puffs', frequencyScore: 94, description: 'Inhalation dose: 2 actuations' },
  { term: '1 drop', category: 'dosage', normalized: '1drop', frequencyScore: 85, description: 'Ophthalmic / otic: 1 drop (1 gtt)' },
  { term: '2 drops', category: 'dosage', normalized: '2drops', frequencyScore: 89, description: 'Ophthalmic / otic: 2 drops (2 gtt)' },
  { term: '1 patch', category: 'dosage', normalized: '1patch', frequencyScore: 84, description: 'Transdermal application: 1 patch' },
  { term: '10 units', category: 'dosage', normalized: '10units', frequencyScore: 86, description: 'Insulin / biologic dose: 10 units' },
  { term: '20 units', category: 'dosage', normalized: '20units', frequencyScore: 85, description: 'Insulin / biologic dose: 20 units' },
];

// 3. Latin Prescription Sig Codes & Instructions (60+ items)
const LATIN_SIG_CODES: MedicalLexiconEntry[] = [
  { term: 'QD', category: 'sig_frequency', normalized: 'qd', frequencyScore: 99, description: 'Quaque Die — Once every day / daily' },
  { term: 'BID', category: 'sig_frequency', normalized: 'bid', frequencyScore: 99, description: 'Bis In Die — Twice a day (approx. every 12 hours)' },
  { term: 'TID', category: 'sig_frequency', normalized: 'tid', frequencyScore: 98, description: 'Ter In Die — Three times a day (approx. every 8 hours)' },
  { term: 'QID', category: 'sig_frequency', normalized: 'qid', frequencyScore: 97, description: 'Quater In Die — Four times a day (approx. every 6 hours)' },
  { term: 'Q4H', category: 'sig_frequency', normalized: 'q4h', frequencyScore: 91, description: 'Quaque 4 Hora — Every 4 hours' },
  { term: 'Q6H', category: 'sig_frequency', normalized: 'q6h', frequencyScore: 93, description: 'Quaque 6 Hora — Every 6 hours' },
  { term: 'Q8H', category: 'sig_frequency', normalized: 'q8h', frequencyScore: 92, description: 'Quaque 8 Hora — Every 8 hours' },
  { term: 'Q12H', category: 'sig_frequency', normalized: 'q12h', frequencyScore: 90, description: 'Quaque 12 Hora — Every 12 hours' },
  { term: 'Q24H', category: 'sig_frequency', normalized: 'q24h', frequencyScore: 86, description: 'Quaque 24 Hora — Every 24 hours' },
  { term: 'Q4-6H', category: 'sig_frequency', normalized: 'q46h', frequencyScore: 91, description: 'Every 4 to 6 hours as needed' },
  { term: 'QOD', category: 'sig_frequency', normalized: 'qod', frequencyScore: 82, description: 'Quaque Altera Die — Every other day' },
  { term: 'QHS', category: 'sig_frequency', normalized: 'qhs', frequencyScore: 96, description: 'Quaque Hora Somni — Every night at bedtime' },
  { term: 'QAM', category: 'sig_frequency', normalized: 'qam', frequencyScore: 95, description: 'Every morning' },
  { term: 'QPM', category: 'sig_frequency', normalized: 'qpm', frequencyScore: 92, description: 'Every evening' },
  { term: 'QWK', category: 'sig_frequency', normalized: 'qwk', frequencyScore: 88, description: 'Once weekly' },
  { term: 'STAT', category: 'sig_frequency', normalized: 'stat', frequencyScore: 94, description: 'Statim — Immediately / at once' },
  { term: 'PO', category: 'sig_route', normalized: 'po', frequencyScore: 99, description: 'Per Os — By mouth / orally' },
  { term: 'SL', category: 'sig_route', normalized: 'sl', frequencyScore: 90, description: 'Sub Lingua — Sublingually / dissolve under tongue' },
  { term: 'PR', category: 'sig_route', normalized: 'pr', frequencyScore: 84, description: 'Per Rectum — Rectally' },
  { term: 'IM', category: 'sig_route', normalized: 'im', frequencyScore: 91, description: 'Intramuscular injection' },
  { term: 'IV', category: 'sig_route', normalized: 'iv', frequencyScore: 96, description: 'Intravenous injection or infusion' },
  { term: 'IVPB', category: 'sig_route', normalized: 'ivpb', frequencyScore: 86, description: 'Intravenous piggyback intermittent infusion' },
  { term: 'SC', category: 'sig_route', normalized: 'sc', frequencyScore: 92, description: 'Sub Cutis — Subcutaneous injection (SQ)' },
  { term: 'SQ', category: 'sig_route', normalized: 'sq', frequencyScore: 90, description: 'Subcutaneous injection' },
  { term: 'TOP', category: 'sig_route', normalized: 'top', frequencyScore: 89, description: 'Topically / apply to affected skin' },
  { term: 'INH', category: 'sig_route', normalized: 'inh', frequencyScore: 88, description: 'Inhalation via oral inhaler' },
  { term: 'NEB', category: 'sig_route', normalized: 'neb', frequencyScore: 87, description: 'Via nebulizer machine' },
  { term: 'OD', category: 'sig_route', normalized: 'od', frequencyScore: 87, description: 'Oculus Dexter — Right eye' },
  { term: 'OS', category: 'sig_route', normalized: 'os', frequencyScore: 87, description: 'Oculus Sinister — Left eye' },
  { term: 'OU', category: 'sig_route', normalized: 'ou', frequencyScore: 89, description: 'Oculus Uterque — Both eyes' },
  { term: 'AD', category: 'sig_route', normalized: 'ad', frequencyScore: 85, description: 'Auris Dextra — Right ear' },
  { term: 'AS', category: 'sig_route', normalized: 'as', frequencyScore: 85, description: 'Auris Sinistra — Left ear' },
  { term: 'AU', category: 'sig_route', normalized: 'au', frequencyScore: 86, description: 'Auris Uterque — Both ears' },
  { term: 'NAS', category: 'sig_route', normalized: 'nas', frequencyScore: 84, description: 'Nasal spray / intranasally' },
  { term: 'TRANSDERM', category: 'sig_route', normalized: 'transderm', frequencyScore: 83, description: 'Transdermal skin patch application' },
  { term: 'AC', category: 'sig_timing', normalized: 'ac', frequencyScore: 93, description: 'Ante Cibum — Before meals' },
  { term: 'PC', category: 'sig_timing', normalized: 'pc', frequencyScore: 93, description: 'Post Cibum — After meals' },
  { term: 'IC', category: 'sig_timing', normalized: 'ic', frequencyScore: 82, description: 'Inter Cibos — Between meals' },
  { term: 'WF', category: 'sig_timing', normalized: 'wf', frequencyScore: 91, description: 'With food / with meals' },
  { term: 'HS', category: 'sig_timing', normalized: 'hs', frequencyScore: 95, description: 'Hora Somni — At bedtime / hour of sleep' },
  { term: 'ACHS', category: 'sig_timing', normalized: 'achs', frequencyScore: 89, description: 'Ante Cibum et Hora Somni — Before meals and at bedtime' },
  { term: 'QAC', category: 'sig_timing', normalized: 'qac', frequencyScore: 85, description: 'Before every meal' },
  { term: 'EM', category: 'sig_timing', normalized: 'em', frequencyScore: 80, description: 'Early morning' },
  { term: 'PRN', category: 'instruction', normalized: 'prn', frequencyScore: 99, description: 'Pro Re Nata — As needed' },
  { term: 'PRN PAIN', category: 'instruction', normalized: 'prnpain', frequencyScore: 96, description: 'As needed for pain' },
  { term: 'PRN NAUSEA', category: 'instruction', normalized: 'prnnausea', frequencyScore: 91, description: 'As needed for nausea or vomiting' },
  { term: 'PRN FEVER', category: 'instruction', normalized: 'prnfever', frequencyScore: 90, description: 'As needed for fever (temperature > 100.4F)' },
  { term: 'NPO', category: 'instruction', normalized: 'npo', frequencyScore: 88, description: 'Nil Per Os — Nothing by mouth' },
  { term: 'TAB', category: 'dosage_form', normalized: 'tab', frequencyScore: 99, description: 'Tablet' },
  { term: 'CAP', category: 'dosage_form', normalized: 'cap', frequencyScore: 98, description: 'Capsule' },
  { term: 'GTT', category: 'dosage_form', normalized: 'gtt', frequencyScore: 90, description: 'Guttae — Drops' },
  { term: 'SUSP', category: 'dosage_form', normalized: 'susp', frequencyScore: 89, description: 'Oral liquid suspension' },
  { term: 'SOLN', category: 'dosage_form', normalized: 'soln', frequencyScore: 88, description: 'Solution' },
  { term: 'OINT', category: 'dosage_form', normalized: 'oint', frequencyScore: 85, description: 'Topical ointment' },
  { term: 'UNG', category: 'dosage_form', normalized: 'ung', frequencyScore: 83, description: 'Unguentum — Ointment' },
  { term: 'CREAM', category: 'dosage_form', normalized: 'cream', frequencyScore: 90, description: 'Topical cream' },
  { term: 'SYR', category: 'dosage_form', normalized: 'syr', frequencyScore: 84, description: 'Syrup' },
  { term: 'SUPP', category: 'dosage_form', normalized: 'supp', frequencyScore: 84, description: 'Suppository' },
  { term: 'AAA', category: 'instruction', normalized: 'aaa', frequencyScore: 86, description: 'Apply to Affected Area' },
  { term: 'UD', category: 'instruction', normalized: 'ud', frequencyScore: 88, description: 'Ut Dictum — As directed' },
  { term: 'UT DICT', category: 'instruction', normalized: 'utdict', frequencyScore: 87, description: 'Ut Dictum — As directed on label' },
  { term: 'DISP', category: 'instruction', normalized: 'disp', frequencyScore: 93, description: 'Dispense quantity (e.g. Disp: #30)' },
  { term: 'REFILLS', category: 'instruction', normalized: 'refills', frequencyScore: 92, description: 'Authorized prescription refills (e.g. Refills: 3)' },
];

export const MASTER_MEDICAL_LEXICON: MedicalLexiconEntry[] = [
  ...RXNORM_MEDICATIONS,
  ...CLINICAL_DOSAGES,
  ...LATIN_SIG_CODES,
];

/**
 * Calculates length-adaptive Damerau-Levenshtein distance with transposition support.
 */
export function damerauLevenshteinDistance(source: string, target: string): number {
  const s = source.toLowerCase();
  const t = target.toLowerCase();
  const slen = s.length;
  const tlen = t.length;
  if (slen === 0) return tlen;
  if (tlen === 0) return slen;

  const d: number[][] = Array.from({ length: slen + 1 }, () => new Array(tlen + 1).fill(0));

  for (let i = 0; i <= slen; i++) d[i][0] = i;
  for (let j = 0; j <= tlen; j++) d[0][j] = j;

  for (let i = 1; i <= slen; i++) {
    for (let j = 1; j <= tlen; j++) {
      const cost = s[i - 1] === t[j - 1] ? 0 : 1;
      d[i][j] = Math.min(
        d[i - 1][j] + 1, // deletion
        d[i][j - 1] + 1, // insertion
        d[i - 1][j - 1] + cost // substitution
      );

      // Transposition
      if (i > 1 && j > 1 && s[i - 1] === t[j - 2] && s[i - 2] === t[j - 1]) {
        d[i][j] = Math.min(d[i][j], d[i - 2][j - 2] + 1);
      }
    }
  }
  return d[slen][tlen];
}

/**
 * Fast in-memory medical terminology search with exact, prefix, substring, and fuzzy matching.
 */
export function searchMedicalLexicon(
  input: string | LexiconSearchOptions
): AutocompleteSuggestion[] {
  if (!input) return [];

  const options: LexiconSearchOptions =
    typeof input === 'string' ? { query: input } : input;

  const rawQuery = (options?.query || '').trim();
  if (!rawQuery) return [];

  const cleanQuery = rawQuery.toLowerCase().replace(/[^a-z0-9]/g, '');
  if (!cleanQuery) return [];

  const maxResults = options.maxResults ?? 6;
  const enableFuzzy = options.enableFuzzy ?? true;
  const queryLen = cleanQuery.length;
  const maxFuzzyDist = queryLen <= 2 ? 0 : queryLen <= 5 ? 1 : 2;

  const results: AutocompleteSuggestion[] = [];
  const seenTerms = new Set<string>();

  for (const entry of MASTER_MEDICAL_LEXICON) {
    if (options.categoryFilter) {
      const filters = Array.isArray(options.categoryFilter)
        ? options.categoryFilter
        : [options.categoryFilter];
      if (!filters.includes(entry.category)) continue;
    }

    if (seenTerms.has(entry.term)) continue;

    const normTerm = entry.normalized;
    const termLower = entry.term.toLowerCase();

    // Contextual boost logic
    let contextBonus = 0;
    if (options.contextPreviousWord) {
      const prevNorm = options.contextPreviousWord.toLowerCase().replace(/[^a-z0-9]/g, '');
      const prevIsMed = RXNORM_MEDICATIONS.some((m) => m.normalized === prevNorm);
      const prevIsDose = CLINICAL_DOSAGES.some((d) => d.normalized === prevNorm);

      if (prevIsMed && entry.category === 'dosage') {
        contextBonus = 80;
      } else if ((prevIsMed || prevIsDose) && (entry.category === 'sig_route' || entry.category === 'dosage_form')) {
        contextBonus = 70;
      } else if (entry.category === 'sig_frequency' || entry.category === 'sig_timing') {
        contextBonus = 60;
      }
    }

    // 1. Exact Match
    if (termLower === rawQuery.toLowerCase() || normTerm === cleanQuery) {
      results.push({
        entry,
        matchType: 'exact',
        score: 1000 + entry.frequencyScore + contextBonus,
        highlightIndices: [0, entry.term.length],
      });
      seenTerms.add(entry.term);
      continue;
    }

    // Also check brand names exact match
    if (entry.brandNames && entry.brandNames.some((b) => b.toLowerCase() === rawQuery.toLowerCase())) {
      results.push({
        entry,
        matchType: 'exact',
        score: 950 + entry.frequencyScore + contextBonus,
        highlightIndices: [0, entry.term.length],
      });
      seenTerms.add(entry.term);
      continue;
    }

    // 2. Prefix Match
    if (termLower.startsWith(rawQuery.toLowerCase()) || normTerm.startsWith(cleanQuery)) {
      const matchLen = rawQuery.length;
      results.push({
        entry,
        matchType: 'prefix',
        score: 500 + (matchLen / entry.term.length) * 100 + entry.frequencyScore * 0.5 + contextBonus,
        highlightIndices: [0, matchLen],
      });
      seenTerms.add(entry.term);
      continue;
    }

    // Check brand name prefix
    if (entry.brandNames && entry.brandNames.some((b) => b.toLowerCase().startsWith(rawQuery.toLowerCase()))) {
      results.push({
        entry,
        matchType: 'prefix',
        score: 450 + entry.frequencyScore * 0.5 + contextBonus,
        highlightIndices: [0, rawQuery.length],
      });
      seenTerms.add(entry.term);
      continue;
    }

    // 3. Substring Match (only for queries >= 3 characters to avoid noisy 2-char collisions)
    if (queryLen >= 3) {
      const subIdx = termLower.indexOf(rawQuery.toLowerCase());
      if (subIdx >= 0) {
        results.push({
          entry,
          matchType: 'substring',
          score: 300 + entry.frequencyScore * 0.4 + contextBonus,
          highlightIndices: [subIdx, subIdx + rawQuery.length],
        });
        seenTerms.add(entry.term);
        continue;
      }
    }

    // 4. Fuzzy Match (Damerau-Levenshtein)
    if (enableFuzzy && queryLen >= 3) {
      const dist = damerauLevenshteinDistance(cleanQuery, normTerm);
      if (dist <= maxFuzzyDist) {
        const similarity = 1.0 - dist / Math.max(queryLen, normTerm.length);
        results.push({
          entry,
          matchType: 'fuzzy',
          score: 200 * similarity + entry.frequencyScore * 0.3 + contextBonus,
          highlightIndices: [0, entry.term.length],
        });
        seenTerms.add(entry.term);
      }
    }
  }

  // Sort descending by score
  results.sort((a, b) => b.score - a.score);
  return results.slice(0, maxResults);
}

/**
 * Returns Look-Alike Sound-Alike warning details for a specific drug term.
 */
export function getLasaWarning(
  term: string
): { isLasa: boolean; confusionWith?: string; warning?: string } | null {
  const clean = term.toLowerCase().replace(/[^a-z0-9]/g, '');
  const found = RXNORM_MEDICATIONS.find(
    (m) =>
      m.normalized === clean ||
      m.term.toLowerCase() === term.toLowerCase() ||
      (m.brandNames && m.brandNames.some((b) => b.toLowerCase() === term.toLowerCase()))
  );

  if (found && found.isLasa) {
    return {
      isLasa: true,
      confusionWith: found.lasaConfusionWith,
      warning: found.lasaWarning,
    };
  }
  return null;
}

/**
 * Returns full English expansion for Latin prescription sig code.
 */
export function getSigExpansion(code: string): string | null {
  const clean = code.toUpperCase().trim();
  const found = LATIN_SIG_CODES.find((s) => s.term.toUpperCase() === clean);
  return found ? found.description : null;
}
